version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=achatdb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app-achat:
    depends_on:
      - mysqldb
    image: zairighayth/achat:1.0.0
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : null,
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "management.endpoints.web.exposure.include" : "health,info,prometheus"

        }'
    stdin_open: true
    tty: true
  front-achat:
    image: zairighayth/front-achat:1.0.0 
    ports:
      - 4200:4200
  mysql-exporter:
    image: prom/mysqld-exporter
    command: 
     - --config.my-cnf=/cfg/.my.cnf
     - --mysqld.address=mysqldb:3306
    volumes:
      - "./.my.cnf:/cfg/.my.cnf"
    ports:
      - 9104:9104
  
volumes:
  db: